random_seed: 10032023
gas:
  element: 87Rb
  N_particles: 2e5
  N_grid: !eval [2**9]
  grid_size: 2e-5
  adimensionalization_length: 780e-9
boundaries:
  cavity_detuning: [-4e6, 0e6, 30]
  lattice_ramp: !eval ["linear_ramp(0, 0, 20, 20e-3)"]
potentials:
  trap:
    omegax: 100
    omegay: 100
  cavity:
    atomic_detuning: 76.6e9
    cavity_decay: 150e3
    cavity_coupling: 1.95e6
    cavity_angle: 0
    pump_angle: !eval [pi/3]
initial_wavefunction:
  gaussian_sigma: 1e-6
propagation:
  imaginary_time:
    time_step: !eval [-1e-7j]
    N_iterations: 5000
    leave_progress_bar: False
  real_time:
    time_step: 1e-7
    final_time: 20e-3
    leave_progress_bar: False
