random_seed: 10032023
gas:
  element: 87Rb
  N_particles: 2e5
  N_grid: !eval [2**9]
  grid_size: 3e-5
  adimensionalization_length: 780e-9
boundaries:
  cavity_detuning: [-4e6, 2e6, 20] #30
  lattice_depth: [0, 30, 30] #30
potentials:
  trap:
    omegax: 100
    omegay: 100
  cavity:
    atomic_detuning: 76.6e9
    cavity_decay: 150e3
    cavity_coupling: 1.95e6
    cavity_angle: 0
    pump_angle: !eval [pi/3]
initial_wavefunction:
  gaussian_sigma: 1e-6
propagation:
  imaginary_time:
    time_step: !eval [-1e-8j]
    N_iterations: 80000
    leave_progress_bar: False
