random_seed: 10032023
gas:
  element: 87Rb
  N_particles: 2e5
  N_grid: !eval [2**8]
  grid_size: 3e-5
  adimensionalization_length: 780e-9
potentials:
  trap:
    omegax: 100
    omegay: 100
  contact:
    a_s: 100
    a_orth: 1e-6
initial_wavefunction:
  gaussian_sigma: 1e-6
propagation:
  imaginary_time:
    time_step: !eval [-5e-8j]
    N_iterations: 100000
    leave_progress_bar: False
